chartVersion: 0.3.0

project:
  name: urbansportsclub

repository:
  name: markmorcos/urbansportsclub
  path: .

deployments:
  - name: urbansportsclub-deployment
    image: markmorcos/urbansportsclub
    env:
      - name: EMAIL
        valueFrom:
          secretKeyRef:
            name: credentials
            key: EMAIL
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: credentials
            key: PASSWORD
      - name: BASE_URL
        value: https://rdr.cx
      - name: REDIS_URL
        valueFrom:
          secretKeyRef:
            name: redis-secret
            key: REDIS_URL
