version: 0.4.6

namespace: urbansportsclub
project: urbansportsclub

services:
  - name: urbansportsclub
    image: ghcr.io/markmorcos/urbansportsclub
    env:
      - name: EMAIL
        valueFrom:
          secretKeyRef:
            name: credentials
            key: EMAIL
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: credentials
            key: PASSWORD
      - name: REDIS_URL
        valueFrom:
          secretKeyRef:
            name: redis-secret
            key: REDIS_URL
